INSERT INTO library.authors (name, biography, birth_date, death_date, user_updated_id, user_inserted_id, created_at, updated_at) VALUES
('George Orwell', 'English novelist and journalist known for his works Animal Farm and 1984.', '1903-06-25', '1950-01-21', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Harper Lee', 'American novelist widely known for To Kill a Mockingbird.', '1926-04-28', '2016-02-19', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('J.K. Rowling', 'British author, best known for the Harry Potter series.', '1965-07-31', NULL, 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Stephen King', 'American author of horror, supernatural fiction, suspense, and fantasy novels.', '1947-09-21', NULL, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Agatha Christie', 'English writer known for her detective novels featuring Hercule Poirot and Miss Marple.', '1890-09-15', '1976-01-12', 2, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Jane Austen', 'English novelist known for her social commentary and wit.', '1775-12-16', '1817-07-18', 4, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mark Twain', 'American writer, humorist, entrepreneur, publisher, and lecturer.', '1835-11-30', '1910-04-21', 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('F. Scott Fitzgerald', 'American novelist and short story writer, known for The Great Gatsby.', '1896-09-24', '1940-12-21', 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ernest Hemingway', 'American novelist, short story writer, and journalist.', '1899-07-21', '1961-07-02', 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Virginia Woolf', 'English writer, considered one of the most important modernist authors.', '1882-01-25', '1941-03-28', 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Charles Dickens', 'English writer and social critic who created some of the world''s best-known fictional characters.', '1812-02-07', '1870-06-09', 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gabriel García Márquez', 'Colombian novelist and winner of the Nobel Prize in Literature.', '1927-03-06', '2014-04-17', 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Toni Morrison', 'American novelist, essayist, book editor, and college professor.', '1931-02-18', '2019-08-05', 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Leo Tolstoy', 'Russian writer who is regarded as one of the greatest authors of all time.', '1828-09-09', '1910-11-20', 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fyodor Dostoevsky', 'Russian novelist, philosopher, short story writer, essayist, and journalist.', '1821-11-11', '1881-02-09', 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Maya Angelou', 'American poet, memoirist, and civil rights activist.', '1928-04-04', '2014-05-28', 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Paulo Coelho', 'Brazilian lyricist and novelist, best known for The Alchemist.', '1947-08-24', NULL, 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Isabel Allende', 'Chilean writer known for novels such as The House of the Spirits.', '1942-08-02', NULL, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Milan Kundera', 'Czech writer known for The Unbearable Lightness of Being.', '1929-04-01', '2023-07-11', 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Haruki Murakami', 'Japanese writer known for surreal novels and short stories.', '1949-01-12', NULL, 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Margaret Atwood', 'Canadian poet, novelist, literary critic, essayist, and environmental activist.', '1939-11-18', NULL, 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Salman Rushdie', 'British Indian novelist and essayist known for Midnight''s Children.', '1947-06-19', NULL, 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Chimamanda Ngozi Adichie', 'Nigerian writer known for her novels and short stories.', '1977-09-15', NULL, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Yuval Noah Harari', 'Israeli public intellectual, historian and professor.', '1976-02-24', NULL, 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Malcolm Gladwell', 'Canadian journalist, author, and public speaker.', '1963-09-03', NULL, 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dan Brown', 'American author best known for his thriller novels.', '1964-06-22', NULL, 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('John Grisham', 'American novelist, attorney, politician, and activist.', '1955-02-08', NULL, 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nicholas Sparks', 'American novelist, screenwriter and philanthropist.', '1965-12-31', NULL, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gillian Flynn', 'American author and television critic known for Gone Girl.', '1971-02-24', NULL, 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suzanne Collins', 'American television writer and author, known for The Hunger Games.', '1962-08-10', NULL, 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rick Riordan', 'American author known for writing the Percy Jackson series.', '1964-06-05', NULL, 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cassandra Clare', 'American author of young adult fiction, known for The Mortal Instruments.', '1973-07-27', NULL, 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sarah J. Maas', 'American fantasy author known for the Throne of Glass series.', '1986-03-05', NULL, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Brandon Sanderson', 'American author of fantasy and science fiction.', '1975-12-19', NULL, 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Neil Gaiman', 'English author of short fiction, novels, comic books, and audio theatre.', '1960-11-10', NULL, 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Terry Pratchett', 'English humorist, satirist, and author of fantasy novels.', '1948-04-28', '2015-03-12', 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Douglas Adams', 'English author, screenwriter, essayist, humorist, satirist and dramatist.', '1952-03-11', '2001-05-11', 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Isaac Asimov', 'American writer and professor of biochemistry, known for science fiction works.', '1920-01-02', '1992-04-06', 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ray Bradbury', 'American author and screenwriter known for Fahrenheit 451.', '1920-08-22', '2012-06-05', 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Philip K. Dick', 'American science fiction writer known for his work exploring sociological themes.', '1928-12-16', '1982-03-02', 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ursula K. Le Guin', 'American author known for works of speculative fiction.', '1929-10-21', '2018-01-22', 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Arthur C. Clarke', 'British science fiction writer, science writer, futurist, and inventor.', '1917-12-16', '2008-03-19', 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Robert A. Heinlein', 'American science fiction writer often called the dean of science fiction writers.', '1907-07-07', '1988-05-08', 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kurt Vonnegut', 'American writer known for his satirical and darkly humorous novels.', '1922-11-11', '2007-04-11', 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Aldous Huxley', 'English writer and philosopher, known for his novels including Brave New World.', '1894-07-26', '1963-11-22', 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Anthony Burgess', 'English writer and composer, best known for A Clockwork Orange.', '1917-02-25', '1993-11-22', 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('William Gibson', 'American-Canadian speculative fiction writer and essayist.', '1948-03-17', NULL, 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Frank Herbert', 'American science fiction author best known for the Dune series.', '1920-10-08', '1986-02-11', 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Octavia Butler', 'American science fiction author who received Hugo and Nebula awards.', '1947-06-22', '2006-02-24', 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lois Lowry', 'American writer known for children''s literature, including The Giver.', '1937-03-20', NULL, 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
