INSERT INTO library.languages (name, created_at, updated_at) VALUES
('English', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Spanish', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('French', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('German', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Italian', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Portuguese', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Russian', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Japanese', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Chinese', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Arabic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Greek', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dutch', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);