INSERT INTO library.publishers (name, address, city, country, email, year, user_updated_id, user_inserted_id, created_at, updated_at) VALUES
('Penguin Random House', '1745 Broadway', 'New York', 'United States', 'contact@penguinrandomhouse.com', '2013-01-01', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('HarperCollins', '195 Broadway', 'New York', 'United States', 'info@harpercollins.com', '1989-01-01', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Simon & Schuster', '1230 Avenue of the Americas', 'New York', 'United States', 'contact@simonandschuster.com', '1924-01-01', 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Macmillan Publishers', '120 Broadway', 'New York', 'United States', 'info@macmillan.com', '1843-01-01', 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hachette Book Group', '1290 Avenue of the Americas', 'New York', 'United States', 'contact@hachettebookgroup.com', '2006-01-01', 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Scholastic Corporation', '557 Broadway', 'New York', 'United States', 'info@scholastic.com', '1920-01-01', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Oxford University Press', 'Great Clarendon Street', 'Oxford', 'United Kingdom', 'enquiry@oup.com', '1586-01-01', 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cambridge University Press', 'University Printing House', 'Cambridge', 'United Kingdom', 'information@cambridge.org', '1534-01-01', 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bloomsbury Publishing', '50 Bedford Square', 'London', 'United Kingdom', 'contact@bloomsbury.com', '1986-01-01', 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Faber & Faber', 'Bloomsbury House', 'London', 'United Kingdom', 'info@faber.co.uk', '1929-01-01', 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vintage Books', '1745 Broadway', 'New York', 'United States', 'vintage@penguinrandomhouse.com', '1954-01-01', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Doubleday', '1745 Broadway', 'New York', 'United States', 'doubleday@penguinrandomhouse.com', '1897-01-01', 1, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Knopf', '1745 Broadway', 'New York', 'United States', 'knopf@penguinrandomhouse.com', '1915-01-01', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Little, Brown and Company', '1290 Avenue of the Americas', 'New York', 'United States', 'info@littlebrown.com', '1837-01-01', 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Grove Atlantic', '154 West 14th Street', 'New York', 'United States', 'info@groveatlantic.com', '1917-01-01', 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('W. W. Norton & Company', '500 Fifth Avenue', 'New York', 'United States', 'info@wwnorton.com', '1923-01-01', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Farrar, Straus and Giroux', '120 Broadway', 'New York', 'United States', 'fsg@macmillan.com', '1946-01-01', 1, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('St. Martin''s Press', '120 Broadway', 'New York', 'United States', 'stmartins@macmillan.com', '1952-01-01', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Crown Publishing Group', '1745 Broadway', 'New York', 'United States', 'crown@penguinrandomhouse.com', '1933-01-01', 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bantam Books', '1745 Broadway', 'New York', 'United States', 'bantam@penguinrandomhouse.com', '1945-01-01', 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Del Rey Books', '1745 Broadway', 'New York', 'United States', 'delrey@penguinrandomhouse.com', '1977-01-01', 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tor Books', '120 Broadway', 'New York', 'United States', 'tor@macmillan.com', '1980-01-01', 1, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ace Books', '375 Hudson Street', 'New York', 'United States', 'ace@penguingroup.com', '1952-01-01', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DAW Books', '375 Hudson Street', 'New York', 'United States', 'daw@penguingroup.com', '1971-01-01', 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Orbit Books', '1290 Avenue of the Americas', 'New York', 'United States', 'orbit@hachettebookgroup.com', '1974-01-01', 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);